/* Capstone Disassembly Engine */

/* AUTOGENERATED by generate_cs_arch_globals.py */
/* DO NOT MODIFY DIRECTLY! */

#include "cs_priv.h"

#include "arch/AArch64/AArch64Module.h"
#include "arch/ARM/ARMModule.h"
#include "arch/Mips/MipsModule.h"
#include "arch/PowerPC/PPCModule.h"
#include "arch/Sparc/SparcModule.h"
#include "arch/SystemZ/SystemZModule.h"
#include "arch/X86/X86Module.h"
#include "arch/XCore/XCoreModule.h"


cs_err (*cs_arch_init[MAX_ARCH])(cs_struct *) = {
#ifdef CAPSTONE_HAS_ARM
	ARM_global_init,
#else
	NULL,
#endif
#ifdef CAPSTONE_HAS_ARM64
	AArch64_global_init,
#else
	NULL,
#endif
#ifdef CAPSTONE_HAS_MIPS
	Mips_global_init,
#else
	NULL,
#endif
#ifdef CAPSTONE_HAS_X86
	X86_global_init,
#else
	NULL,
#endif
#ifdef CAPSTONE_HAS_POWERPC
	PPC_global_init,
#else
	NULL,
#endif
#ifdef CAPSTONE_HAS_SPARC
	Sparc_global_init,
#else
	NULL,
#endif
#ifdef CAPSTONE_HAS_SYSZ
	SystemZ_global_init,
#else
	NULL,
#endif
#ifdef CAPSTONE_HAS_XCORE
	XCore_global_init,
#else
	NULL,
#endif
};

cs_err (*cs_arch_option[MAX_ARCH]) (cs_struct *, cs_opt_type, size_t value) = {
#ifdef CAPSTONE_HAS_ARM
	ARM_option,
#else
	NULL,
#endif
#ifdef CAPSTONE_HAS_ARM64
	AArch64_option,
#else
	NULL,
#endif
#ifdef CAPSTONE_HAS_MIPS
	Mips_option,
#else
	NULL,
#endif
#ifdef CAPSTONE_HAS_X86
	X86_option,
#else
	NULL,
#endif
#ifdef CAPSTONE_HAS_POWERPC
	PPC_option,
#else
	NULL,
#endif
#ifdef CAPSTONE_HAS_SPARC
	Sparc_option,
#else
	NULL,
#endif
#ifdef CAPSTONE_HAS_SYSZ
	SystemZ_option,
#else
	NULL,
#endif
#ifdef CAPSTONE_HAS_XCORE
	XCore_option,
#else
	NULL,
#endif
};

void (*cs_arch_destroy[MAX_ARCH]) (cs_struct *) = {
#ifdef CAPSTONE_HAS_ARM
	ARM_destroy,
#else
	NULL,
#endif
#ifdef CAPSTONE_HAS_ARM64
	AArch64_destroy,
#else
	NULL,
#endif
#ifdef CAPSTONE_HAS_MIPS
	Mips_destroy,
#else
	NULL,
#endif
#ifdef CAPSTONE_HAS_X86
	X86_destroy,
#else
	NULL,
#endif
#ifdef CAPSTONE_HAS_POWERPC
	PPC_destroy,
#else
	NULL,
#endif
#ifdef CAPSTONE_HAS_SPARC
	Sparc_destroy,
#else
	NULL,
#endif
#ifdef CAPSTONE_HAS_SYSZ
	SystemZ_destroy,
#else
	NULL,
#endif
#ifdef CAPSTONE_HAS_XCORE
	XCore_destroy,
#else
	NULL,
#endif
};

cs_mode cs_arch_disallowed_mode_mask[MAX_ARCH] = {
#ifdef CAPSTONE_HAS_ARM
	~(CS_MODE_LITTLE_ENDIAN | CS_MODE_ARM | CS_MODE_V8 | CS_MODE_MCLASS | CS_MODE_THUMB | CS_MODE_BIG_ENDIAN),
#else
	0,
#endif
#ifdef CAPSTONE_HAS_ARM64
	~(CS_MODE_LITTLE_ENDIAN | CS_MODE_ARM | CS_MODE_BIG_ENDIAN),
#else
	0,
#endif
#ifdef CAPSTONE_HAS_MIPS
	~(CS_MODE_LITTLE_ENDIAN | CS_MODE_32 | CS_MODE_64 | CS_MODE_MICRO | CS_MODE_MIPS32R6 | CS_MODE_MIPSGP64 | CS_MODE_BIG_ENDIAN),
#else
	0,
#endif
#ifdef CAPSTONE_HAS_X86
	~(CS_MODE_LITTLE_ENDIAN | CS_MODE_32 | CS_MODE_64 | CS_MODE_16),
#else
	0,
#endif
#ifdef CAPSTONE_HAS_POWERPC
	~(CS_MODE_LITTLE_ENDIAN | CS_MODE_32 | CS_MODE_64 | CS_MODE_BIG_ENDIAN),
#else
	0,
#endif
#ifdef CAPSTONE_HAS_SPARC
	~(CS_MODE_BIG_ENDIAN | CS_MODE_V9),
#else
	0,
#endif
#ifdef CAPSTONE_HAS_SYSZ
	~(CS_MODE_BIG_ENDIAN),
#else
	0,
#endif
#ifdef CAPSTONE_HAS_XCORE
	~(CS_MODE_BIG_ENDIAN),
#else
	0,
#endif
};

unsigned int all_arch =
#ifdef CAPSTONE_HAS_ARM
	(1 << CS_ARCH_ARM)
#else
	0
#endif
	|
#ifdef CAPSTONE_HAS_ARM64
	(1 << CS_ARCH_ARM64)
#else
	0
#endif
	|
#ifdef CAPSTONE_HAS_MIPS
	(1 << CS_ARCH_MIPS)
#else
	0
#endif
	|
#ifdef CAPSTONE_HAS_X86
	(1 << CS_ARCH_X86)
#else
	0
#endif
	|
#ifdef CAPSTONE_HAS_POWERPC
	(1 << CS_ARCH_PPC)
#else
	0
#endif
	|
#ifdef CAPSTONE_HAS_SPARC
	(1 << CS_ARCH_SPARC)
#else
	0
#endif
	|
#ifdef CAPSTONE_HAS_SYSZ
	(1 << CS_ARCH_SYSZ)
#else
	0
#endif
	|
#ifdef CAPSTONE_HAS_XCORE
	(1 << CS_ARCH_XCORE)
#else
	0
#endif
	;
